### ISSUE TITLE
Support dump files

### ISSUE THREAD

**Issue by gersonfs** [vierge-noire/cakephp-test-migrator#14]
Hello!

I am trying to use this plugin in an existing CakePHP 4 project. However, after changing the PHPUnit configuration file, my tests no longer run. The error it presents is:

Base table or view not found: 1146 Table 'database.table' doesn't exist.

In all my current fixtures, I import the table definition of the default connection, using
`public $import = ['table' => 'table_name'];`

How can I use the plugin but keep the current tests working?

In the CI / CD pipeline we execute a .sql file with all CREATE TABLE in the default connection.
We do not use the Migrations plugin, as we have a legacy system since the time of Cake 1. Migrations at that time did not meet our requirements.
In the pipeline it will be easy to execute this SQL file in the test connection, but I think what it would be like in a development environment when running a single test class. Currently, the complete database contains almost 300 tables. Performing the creation of all of these tables before a single test would be costly.

**Comment by pabloelcolombiano** [comment]
Hello!

I have pushed a solution to your issue on the `next` branch, respectively `cake3_next`.

The documentation is here: https://github.com/vierge-noire/cakephp-test-migrator/tree/next#what-if-i-do-not-use-migrations

The schema will be recreated prior to each test run (not each test though). But you can easily come up with a solution where you would run the dump only of the last of your inserted table is not present. This somewhat simulate the migration paradigm and have your test suite start faster.

You can consequently remove import in the CI.

Would you mind checking that the solution proposed matches your issue? If so, I would create a new tag.

PS: this said, you should probably be able to create an initial migration from your dump and start using migrations based on that.
https://book.cakephp.org/migrations/2/en/index.html#generating-migrations-from-an-existing-database

**Comment by gersonfs** [comment]
I believe that the solution will meet our requirements.
As suggested, we will evaluate the adoption of the CakePHP Migrations plugin.
