### ISSUE TITLE
Allow check for migrations

### ISSUE THREAD

**Issue by raul338** [vierge-noire/cakephp-test-migrator#20]
Hi!

I would like to check if there is a migration pending, but instead of runing migrations, i would launch another command.

In my case this command runs migrations, run some other commands and bake some fixtures (e.g [ACL](https://github.com/cakephp/acl/) acos table)

I think that adding a wrapper for `isStatusChanged` would suffice. So I can do something like this:

```php
$migrator = CakephpTestMigrator\Migrator(true);
$migrator->configReader->readMigrationsInDatasources();
$migrator->configReader->readConfig([
   ['plugin' => 'Acl'],
   []
]);
if ($migrator->isStatusChanged()) {
   // launch commands, run migrations, re-bake fixtures, etc
}
```

If you agree i can try open a PR

Thanks for the plugin!

**Comment by pabloelcolombiano** [comment]
Hi @raul338 ,
Thanks for the input. How about having $result = Migrator::migrate() return a Boolean true if the status changed? Or an array with the list of configs that changed?

**Comment by raul338** [comment]
Hi @pabloelcolombiano 

Yes something like that would work. So to trigger some code/command to execute after migrations are done if any.

**Comment by pabloelcolombiano** [comment]
Hi @raul338
what do you think of this [PR](https://github.com/vierge-noire/cakephp-test-migrator/pull/21)? Would this fix your issue?

**Comment by raul338** [comment]
Yes! it works, Thanks!

**Comment by pabloelcolombiano** [comment]
This is now handled by v2.4. Thanks for the input @raul338 !
