### ISSUE TITLE
Allow to truncating tables later

### ISSUE THREAD

**Issue by raul338** [vierge-noire/cakephp-test-migrator#23]
Related to #20

I have a project where in some tables i have inserted some constants, like this

```php
$table->addColumn('name', 'string');
// $table->addColumn(...);
$table->create();
$table->insert([
    [
        'id' => \App\Model\Entity\ArticleStates::ARTICLE_NEW,
        'name' => 'New',
        // ...
    ],
    // ....
]);
$table->save();
```

When using the migrator, if migrations changed, I bake fixtures but this results empty because the migrator truncates it.
```php
// tests/bootstrap.php
$migrator = \CakephpTestMigrator\Migrator::migrate();
$modified = $migrator->getConnectionsWithModifiedStatus();
if (count($modified)) {
   // re-bake fixtures... 
   // here i would need the db not truncated
   // and call "truncate()" manually
}
```

A solution could be passing an options array for second parameter of `Migrator::migrate()`

**Comment by pabloelcolombiano** [comment]
Hi @raul338 ,

The aim of the Migrator is to provide a clean updated schema, for the test database(s). Since the data base is dropped before each tests, the data inserted in the migrations are bound to be dropped, there is no way around. In your case, which I encounter regularly, I would suggest to populate the data inserted by your migrations with fixture factories in the setup() method of the tests that will require those entities.

Those this make sense, or am I missing your point?

**Comment by raul338** [comment]
Thats what my tooling helps. It bakes the `ArticleStates` fixture with the result of the migration. The fixture is "reset" in every `setUp()`

Its the fixture content I want to refresh after the migrations are done, in case a new migration adds a row/constant. This avoid manual mainteniance on the fixture (keeping the migrations as the source of truth, instead of manually keep 2 lists in sync)

Another solution (i've not tested yet) would be to trigger an event before truncation. I just need to execute a shell before truncating.

**Comment by pabloelcolombiano** [comment]
I like the idea of the events. We could have
• before truncate
• after truncate
• after tear down

With as event subject some object with information on which tables were truncated.

**Comment by raul338** [comment]
Do you mean between tests?
I mean to run it once in the bootstrap before all the tests are executed.
To me only the same array in `getConnectionsWithModifiedStatus` would suffice

**Comment by pabloelcolombiano** [comment]
O.K. I now get the complete picture. I guess it would have been better to separate migration from truncation in two different methods, so one could call:
```
$migrator = Migrator::migrate();
// Do some stuff
// and then
$migrator->truncate(); 
```

But doing this now will produce some backward compatibility issues.
The idea with the events is good, but I was thinking more of the [test suite light](https://github.com/vierge-noire/cakephp-test-suite-light), where it could be very useful.

 What I can do, is:
1.  adding a `$truncate` parameter to the  `migrate(array $config = [], bool $verbose = false, bool $truncate = true)` method
2. put the `truncation(?array $connections)` in a separate public function, that can be called later
3. if `$connections` is not provided, all `connectionsWithModifiedStatus` get truncated.

How about that?

**Comment by raul338** [comment]
That works!

I think this will be more future-proof
```php
/**
 * @param array{verbose:?bool, truncate: ?bool} $options
 */
migrate(array $config = [], $options)
```

**Comment by pabloelcolombiano** [comment]
Yes, I agree. And it can support BC. Let me discuss this with @pakacuda and we'll go for it. You are also welcome to send a PR!

**Comment by pabloelcolombiano** [comment]
This is now featured in [v2.5](https://github.com/vierge-noire/cakephp-test-migrator/releases/tag/v2.5). Thanks for the contribution!
