### ISSUE TITLE
Migrator is always truncating table though no migrations have been done

### ISSUE THREAD

**Issue by liqueurdetoile** [vierge-noire/cakephp-test-migrator#28]
Hello @pabloelcolombiano 

I'm there again ^^ Hope you're going well.

I was upgrading an app from 4.2x to 4.3x. and so vierge-noire packages. After upgrading, a really simple TestCase that implies no database interaction was badly delayed at start (I was previously using `skipTablesTruncation` trait).

By now, I'm on 4.3.8 for cakephp and 2.5 for migrator on this app.

I've first applied the "fixture upgrade" but it didn't help.

The culprit is the migrator that was running truncations on all tables though no migration have been deployed. I've disabled truncation as explained and now it rocks again.

BUT I'm wondering why this test was launching so quickly in the previous setup and not in the new ? By the way, why choosing to truncate tables as default after a migration in the test environment that should be "hand-cleaned" if needed before the TestCase/test ?

Unfortunately, I don't have any time by now to figure it out so I'm opening this issue . If it seems non relevant to you, feel free to close it 😄

**Comment by pabloelcolombiano** [comment]
Hi @liqueurdetoile,

nice to see you back! The Migrator has been integrated int the [migration plugin](https://github.com/cakephp/migrations/releases/tag/3.3.0). I have just updated the docs [here](https://github.com/vierge-noire/cakephp-test-migrator/blob/main/README.md#for-cakephp-43).

I suggest you now use the migrations' migrator. If you observe the same performance issue, feel free to open an issue there, and to ping me, I'll have a look at it.

Performance issues are very relevant! Thanks for the hint.
